version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/server
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root